name: summaraizer
description: AI Video Assistant Flutter app

publish_to: 'none' # Paket yayınlanmayacaksa

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  file_picker: ^6.1.1
  # Eğer mikrofon kaydı için ekleyeceksen, örneğin:
  # record: ^4.4.0

  # Diğer Flutter standart paketleri
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

